# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bars_model',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
