# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bars_app', '0004_bars_location_model_cuisines'),
    ]

    operations = [
        migrations.AddField(
            model_name='bars_location_model',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
