# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars_app', '0006_auto_20170824_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='bars_location_model',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bars_location_model',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
