# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars_app', '0008_auto_20170824_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='bars_location_model',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
