# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 10:11
from __future__ import unicode_literals

import bars_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars_app', '0010_auto_20170825_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bars_location_model',
            name='cuisines',
            field=models.CharField(blank=True, max_length=450, null=True, validators=[bars_app.validators.validate_cuisines]),
        ),
    ]
