# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 05:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bars_app', '0012_bars_location_model_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bars_location_model',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bars', to=settings.AUTH_USER_MODEL),
        ),
    ]
